%% ========================================================================
%  57BLDC75-20730-08B21 MOTOR - STEADY-STATE CHARACTERIZATION
%
%  ONLY STEADY-STATE OPERATING POINTS ARE CALCULATED:
%
%       di/dt     = 0
%       domega/dt = 0
%
%  Therefore:
%
%       0 = V - R*i - Ke*omega
%       0 = Kt*i - B*omega - Tload
%
%
%  CASE 1:
%    - Constant voltage = 24 V
%    - Load torque increases from 0 to the selected maximum
%    - Current limit selectable:
%         1.0 A -> Driver limit
%         4.8 A -> Motor rated-current limit
%
%    FIGURE:
%       Current    vs Load Torque
%       Efficiency vs Load Torque
%       Power      vs Load Torque
%       RPM        vs Load Torque
%
%
%  CASE 2:
%    - Zero external load torque
%    - Voltage sweep from 6 V to 24 V
%    - Current limit selectable:
%         1.0 A -> Driver limit
%         4.8 A -> Motor rated-current limit
%
%    FIGURE:
%       RPM vs Commanded Voltage
%
%
%  OUTPUT:
%
%    Figure 1:
%       Case1_LoadTorque_Characteristics.png
%
%    Figure 2:
%       Case2_Voltage_vs_RPM.png
%
%    Excel:
%       Motor_Simulation_Results.xlsx
%
% ========================================================================

clear;
clc;
close all force;


%% ========================================================================
%  1. MOTOR PARAMETERS
%  ========================================================================

motor.model = '57BLDC75-20730-08B21';


%% Datasheet identification

motor.numberOfPoles  = 4;
motor.numberOfPhases = 3;


%% Datasheet operating parameters

motor.nominalVoltage = 24;      % [V]

motor.ratedSpeedRPM  = 4000;    % [RPM]

motor.ratedTorque    = 0.22;    % [N*m]

motor.ratedCurrent   = 4.8;     % [A]

motor.ratedPower     = 70;      % [W]

motor.peakTorque     = 0.66;    % [N*m]

motor.peakCurrent    = 14.4;    % [A]


%% ========================================================================
%  2. TORQUE CONSTANT
%  ========================================================================

motor.Kt = 0.06;                % [N*m/A]


%% ========================================================================
%  3. BACK-EMF CONSTANT
%  ========================================================================

motor.Ke_V_per_kRPM = 6.6;      % [V/kRPM]


motor.Ke = ...
    motor.Ke_V_per_kRPM / ...
    (1000*2*pi/60);             % [V/(rad/s)]


%% ========================================================================
%  4. ELECTRICAL PARAMETERS
%  ========================================================================

motor.R = 0.48;                 % [ohm]

motor.L = 1.17e-3;              % [H]


%% ========================================================================
%  5. ROTOR AND LOAD INERTIA
%  ========================================================================

motor.rotorInertia_gcm2 = 119;  % [g*cm^2]


motor.Jmotor = ...
    motor.rotorInertia_gcm2 * ...
    1e-7;                       % [kg*m^2]


motor.Jload = 2.5e-4;           % [kg*m^2]


motor.J = ...
    motor.Jmotor + ...
    motor.Jload;                % [kg*m^2]


%% ========================================================================
%  6. VISCOUS FRICTION COEFFICIENT
%  ========================================================================

motor.noLoadCurrent = 0.3;      % [A]

motor.noLoadSpeedRPM = 4000;    % [RPM]


motor.noLoadAngularVelocity = ...
    motor.noLoadSpeedRPM * ...
    2*pi/60;                    % [rad/s]


motor.B = ...
    motor.Kt * ...
    motor.noLoadCurrent / ...
    motor.noLoadAngularVelocity;
                                % [N*m*s/rad]


%% ========================================================================
%  7. GENERAL CHARACTERIZATION PARAMETERS
%  ========================================================================

simulation.numberOfOperatingPoints = 3000;

simulation.maximumPlotPoints = 3000;


%% ========================================================================
%  8. GRAPHICS AND FILE SETTINGS
%  ========================================================================

set( ...
    groot, ...
    'defaultFigureRenderer', ...
    'painters' ...
);


output.figure1File = ...
    'Case1_LoadTorque_Characteristics.png';


output.figure2File = ...
    'Case2_Voltage_vs_RPM.png';


output.excelFile = ...
    'Motor_Simulation_Results.xlsx';


output.figureResolution = 300;


%% ========================================================================
%  9. PRINT MOTOR PARAMETERS
%  ========================================================================

fprintf('\n============================================================\n');
fprintf('57BLDC75-20730-08B21 STEADY-STATE MOTOR MODEL\n');
fprintf('============================================================\n');


fprintf('\nMotor parameters:\n\n');


fprintf( ...
    'Resistance:                 %.6f ohm\n', ...
    motor.R ...
);


fprintf( ...
    'Inductance:                 %.6e H\n', ...
    motor.L ...
);


fprintf( ...
    'Torque constant:            %.6f N*m/A\n', ...
    motor.Kt ...
);


fprintf( ...
    'Back-EMF constant:          %.6f V/(rad/s)\n', ...
    motor.Ke ...
);


fprintf( ...
    'Total inertia:              %.6e kg*m^2\n', ...
    motor.J ...
);


fprintf( ...
    'Viscous friction:           %.6e N*m*s/rad\n', ...
    motor.B ...
);


fprintf( ...
    'Rated speed:                %.0f RPM\n', ...
    motor.ratedSpeedRPM ...
);


fprintf( ...
    'Rated current:              %.2f A\n', ...
    motor.ratedCurrent ...
);


fprintf('\nSteady-state conditions:\n');

fprintf('di/dt     = 0\n');

fprintf('domega/dt = 0\n');


fprintf( ...
    'Operating points:           %d\n', ...
    simulation.numberOfOperatingPoints ...
);


%% ========================================================================
%  ========================================================================
%
%                              CASE 1
%
%                CONSTANT 24 V + LOAD TORQUE SWEEP
%
%  ========================================================================
%  ========================================================================


%% ========================================================================
%  10. CASE 1 PARAMETERS
%  ========================================================================

case1.voltage = 24;             % [V]

case1.initialLoadTorque = 0.00; % [N*m]

case1.finalLoadTorque = 0.2;    % [N*m]

case1.minimumCurrent = 0;       % [A]


%% ========================================================================
%  CASE 1 CURRENT LIMIT SELECTION
%  ========================================================================

% -------------------------------------------------------------------------
%
% ACTIVE:
%
%       Driver current limit = 1 A
%
% COMMENT THIS LINE:
%
%       Motor rated-current limit = 4.8 A
%
% -------------------------------------------------------------------------

case1.maximumCurrent = 1.0;     % DRIVER LIMIT - COMMENT FOR 4.8 A


if ~isfield(case1,'maximumCurrent')

    case1.maximumCurrent = ...
        motor.ratedCurrent;

end


if abs(case1.maximumCurrent - 1.0) < 1e-9

    case1.currentLimitSource = ...
        'Driver limit';

elseif abs( ...
        case1.maximumCurrent - ...
        motor.ratedCurrent ...
        ) < 1e-9

    case1.currentLimitSource = ...
        'Motor rated current';

else

    case1.currentLimitSource = ...
        'Custom current limit';

end


%% ========================================================================
%  11. CASE 1 LOAD TORQUE SWEEP
%  ========================================================================

loadTorque1 = linspace( ...
    case1.initialLoadTorque, ...
    case1.finalLoadTorque, ...
    simulation.numberOfOperatingPoints ...
).';


commandedVoltage1 = ...
    case1.voltage * ...
    ones(size(loadTorque1));


%% ========================================================================
%  12. CASE 1 STEADY-STATE SOLUTION
%  ========================================================================

numberOfSamples1 = ...
    length(loadTorque1);


current1 = ...
    zeros(numberOfSamples1,1);


angularVelocity1 = ...
    zeros(numberOfSamples1,1);


effectiveVoltage1 = ...
    zeros(numberOfSamples1,1);


currentLimitActive1 = ...
    false(numberOfSamples1,1);


stalledState1 = ...
    false(numberOfSamples1,1);


for k = 1:numberOfSamples1

    [ ...
        current1(k), ...
        angularVelocity1(k), ...
        effectiveVoltage1(k), ...
        currentLimitActive1(k), ...
        stalledState1(k) ...
    ] = steadyStateOperatingPoint( ...
        commandedVoltage1(k), ...
        loadTorque1(k), ...
        motor, ...
        case1.minimumCurrent, ...
        case1.maximumCurrent ...
    );

end


%% ========================================================================
%  13. CASE 1 RPM
%  ========================================================================

motorRPM1 = ...
    angularVelocity1 * ...
    60/(2*pi);


%% ========================================================================
%  14. CASE 1 STALL DETECTION
%  ========================================================================

stallIndex1 = find( ...
    stalledState1 & ...
    loadTorque1 > ...
    case1.initialLoadTorque, ...
    1, ...
    'first' ...
);


if ~isempty(stallIndex1)

    stallDetected1 = true;

    lastIndex1 = ...
        stallIndex1;

else

    stallDetected1 = false;

    lastIndex1 = ...
        length(loadTorque1);

end


%% Keep only points up to stall

loadTorque1 = ...
    loadTorque1(1:lastIndex1);


commandedVoltage1 = ...
    commandedVoltage1(1:lastIndex1);


current1 = ...
    current1(1:lastIndex1);


angularVelocity1 = ...
    angularVelocity1(1:lastIndex1);


effectiveVoltage1 = ...
    effectiveVoltage1(1:lastIndex1);


currentLimitActive1 = ...
    currentLimitActive1(1:lastIndex1);


stalledState1 = ...
    stalledState1(1:lastIndex1);


motorRPM1 = ...
    motorRPM1(1:lastIndex1);


%% ========================================================================
%  15. CASE 1 MOTOR VARIABLES
%  ========================================================================

%% Electromagnetic motor torque

motorTorque1 = ...
    motor.Kt .* ...
    current1;


%% Back EMF

backEMF1 = ...
    motor.Ke .* ...
    angularVelocity1;


%% Friction torque

frictionTorque1 = ...
    motor.B .* ...
    angularVelocity1;


%% Net torque

netTorque1 = ...
    motorTorque1 - ...
    loadTorque1 - ...
    frictionTorque1;


%% ========================================================================
%  16. CASE 1 POWERS
%  ========================================================================

%% Electrical input power

electricalPower1 = ...
    effectiveVoltage1 .* ...
    current1;


%% Electromagnetic mechanical power

motorMechanicalPower1 = ...
    motorTorque1 .* ...
    angularVelocity1;


%% Useful load power

loadMechanicalPower1 = ...
    loadTorque1 .* ...
    angularVelocity1;


%% ========================================================================
%  17. CASE 1 STEADY-STATE EFFICIENCY
%  ========================================================================

% Useful output power:
%
%       Pout = Tload * omega
%
% Electrical input power:
%
%       Pin = Veff * i
%
% Efficiency:
%
%                Pout
%       eta = ----------- * 100
%                Pin


efficiency1 = ...
    zeros(size(loadTorque1));


validEfficiency1 = ...
    electricalPower1 > 1e-12;


efficiency1(validEfficiency1) = ...
    100 .* ...
    loadMechanicalPower1(validEfficiency1) ./ ...
    electricalPower1(validEfficiency1);


efficiency1 = ...
    min( ...
        max( ...
            efficiency1, ...
            0 ...
        ), ...
        100 ...
    );


%% ========================================================================
%  18. CASE 1 RESULTS
%  ========================================================================

fprintf('\n============================================================\n');
fprintf('CASE 1 - LOAD TORQUE CHARACTERIZATION\n');
fprintf('============================================================\n');


fprintf( ...
    'Voltage:                       %.2f V\n', ...
    case1.voltage ...
);


fprintf( ...
    'Current limit:                 %.2f A\n', ...
    case1.maximumCurrent ...
);


fprintf( ...
    'Current limit source:          %s\n', ...
    case1.currentLimitSource ...
);


fprintf( ...
    'No-load steady-state speed:    %.2f RPM\n', ...
    motorRPM1(1) ...
);


fprintf( ...
    'No-load steady-state current:  %.4f A\n', ...
    current1(1) ...
);


fprintf( ...
    'Maximum simulated current:     %.4f A\n', ...
    max(current1) ...
);


fprintf( ...
    'Maximum electromagnetic torque: %.4f N*m\n', ...
    max(motorTorque1) ...
);


fprintf( ...
    'Maximum electrical power:      %.2f W\n', ...
    max(electricalPower1) ...
);


fprintf( ...
    'Maximum mechanical power:      %.2f W\n', ...
    max(motorMechanicalPower1) ...
);


fprintf( ...
    'Maximum load output power:     %.2f W\n', ...
    max(loadMechanicalPower1) ...
);


fprintf( ...
    'Maximum efficiency:            %.2f %%\n', ...
    max(efficiency1) ...
);


%% Maximum efficiency operating point

[maximumEfficiency1, ...
 maximumEfficiencyIndex1] = ...
    max(efficiency1);


fprintf( ...
    'Torque at maximum efficiency:  %.4f N*m\n', ...
    loadTorque1(maximumEfficiencyIndex1) ...
);


fprintf( ...
    'Speed at maximum efficiency:   %.2f RPM\n', ...
    motorRPM1(maximumEfficiencyIndex1) ...
);


%% Maximum useful output power operating point

[maximumOutputPower1, ...
 maximumOutputPowerIndex1] = ...
    max(loadMechanicalPower1);


fprintf( ...
    'Torque at maximum output power: %.4f N*m\n', ...
    loadTorque1(maximumOutputPowerIndex1) ...
);


fprintf( ...
    'Speed at maximum output power:  %.2f RPM\n', ...
    motorRPM1(maximumOutputPowerIndex1) ...
);


if stallDetected1

    fprintf('\nMOTOR STALL DETECTED\n');


    fprintf( ...
        'Load torque at stall:          %.4f N*m\n', ...
        loadTorque1(end) ...
    );


    fprintf( ...
        'Current at stall:              %.4f A\n', ...
        current1(end) ...
    );

else

    fprintf('\nNo motor stall detected within selected torque range.\n');

end


%% ========================================================================
%  19. CASE 1 PLOT DATA
%  ========================================================================

numberPlotPoints1 = min( ...
    simulation.maximumPlotPoints, ...
    length(loadTorque1) ...
);


plotIndex1 = ...
    unique( ...
        round( ...
            linspace( ...
                1, ...
                length(loadTorque1), ...
                numberPlotPoints1 ...
            ) ...
        ) ...
    );


%% ========================================================================
%  20. FIGURA 1 - CURVAS CARACTERISTICAS CASO 1
%  ========================================================================

figure1 = figure( ...
    'Name', ...
    'CASO 1 - Curvas características en función del torque de carga', ...
    'NumberTitle','off', ...
    'Color','white', ...
    'Renderer','painters' ...
);


set( ...
    figure1, ...
    'Position', ...
    [80 60 1400 800] ...
);


%% ------------------------------------------------------------------------
%  Corriente vs Torque de carga
%  ------------------------------------------------------------------------

ax11 = subplot(2,2,1);


plot( ...
    ax11, ...
    loadTorque1(plotIndex1), ...
    current1(plotIndex1), ...
    'LineWidth',1.7 ...
);


hold(ax11,'on');


yline( ...
    ax11, ...
    case1.maximumCurrent, ...
    '--', ...
    sprintf( ...
        'Límite de corriente: %.1f A', ...
        case1.maximumCurrent ...
    ), ...
    'LineWidth',1.1 ...
);


hold(ax11,'off');


grid(ax11,'on');

box(ax11,'on');


xlabel( ...
    ax11, ...
    'Torque de carga [N·m]' ...
);


ylabel( ...
    ax11, ...
    'Corriente [A]' ...
);


title( ...
    ax11, ...
    'Corriente vs. torque de carga' ...
);


%% ------------------------------------------------------------------------
%  Eficiencia vs Torque de carga
%  ------------------------------------------------------------------------

ax12 = subplot(2,2,2);


plot( ...
    ax12, ...
    loadTorque1(plotIndex1), ...
    efficiency1(plotIndex1), ...
    'LineWidth',1.7 ...
);


grid(ax12,'on');

box(ax12,'on');


xlabel( ...
    ax12, ...
    'Torque de carga [N·m]' ...
);


ylabel( ...
    ax12, ...
    'Eficiencia [%]' ...
);


title( ...
    ax12, ...
    'Eficiencia estacionaria vs. torque de carga' ...
);


ylim( ...
    ax12, ...
    [0 100] ...
);


%% ------------------------------------------------------------------------
%  Potencia vs Torque de carga
%  ------------------------------------------------------------------------

ax13 = subplot(2,2,3);


plot( ...
    ax13, ...
    loadTorque1(plotIndex1), ...
    electricalPower1(plotIndex1), ...
    'LineWidth',1.5 ...
);


hold(ax13,'on');


plot( ...
    ax13, ...
    loadTorque1(plotIndex1), ...
    motorMechanicalPower1(plotIndex1), ...
    '--', ...
    'LineWidth',1.5 ...
);


plot( ...
    ax13, ...
    loadTorque1(plotIndex1), ...
    loadMechanicalPower1(plotIndex1), ...
    ':', ...
    'LineWidth',1.7 ...
);


hold(ax13,'off');


grid(ax13,'on');

box(ax13,'on');


xlabel( ...
    ax13, ...
    'Torque de carga [N·m]' ...
);


ylabel( ...
    ax13, ...
    'Potencia [W]' ...
);


title( ...
    ax13, ...
    'Potencia vs. torque de carga' ...
);


legend( ...
    ax13, ...
    'Potencia eléctrica de entrada', ...
    'Potencia mecánica del motor', ...
    'Potencia absorbida por la carga', ...
    'Location','best' ...
);


%% ------------------------------------------------------------------------
%  Velocidad del rotor vs Torque de carga
%  ------------------------------------------------------------------------

ax14 = subplot(2,2,4);


plot( ...
    ax14, ...
    loadTorque1(plotIndex1), ...
    motorRPM1(plotIndex1), ...
    'LineWidth',1.7 ...
);


hold(ax14,'on');


yline( ...
    ax14, ...
    motor.ratedSpeedRPM, ...
    ':', ...
    sprintf( ...
        'Velocidad nominal: %.0f RPM', ...
        motor.ratedSpeedRPM ...
    ), ...
    'LineWidth',1.1 ...
);


hold(ax14,'off');


grid(ax14,'on');

box(ax14,'on');


xlabel( ...
    ax14, ...
    'Torque de carga [N·m]' ...
);


ylabel( ...
    ax14, ...
    'Velocidad del rotor [RPM]' ...
);


title( ...
    ax14, ...
    'Velocidad del rotor vs. torque de carga' ...
);


%% Título general

sgtitle( ...
    sprintf( ...
        ['CASO 1 - Curvas características a 24 V, ' ...
         'límite de corriente = %.1f A'], ...
        case1.maximumCurrent ...
    ), ...
    'FontWeight','bold', ...
    'FontSize',15 ...
);


set( ...
    [ax11 ax12 ax13 ax14], ...
    'FontSize',10, ...
    'LineWidth',0.8, ...
    'Layer','top' ...
);


drawnow;


%% ========================================================================
%  ========================================================================
%
%                              CASE 2
%
%                  ZERO LOAD + VOLTAGE SWEEP
%
%                        6 V TO 24 V
%
%  ========================================================================
%  ========================================================================


%% ========================================================================
%  21. CASE 2 PARAMETERS
%  ========================================================================

case2.initialVoltage = 6;       % [V]

case2.finalVoltage = 24;        % [V]

case2.loadTorque = 0;           % [N*m]

case2.minimumCurrent = 0;       % [A]


%% ========================================================================
%  CASE 2 CURRENT LIMIT SELECTION
%  ========================================================================

% -------------------------------------------------------------------------
%
% ACTIVE:
%
%       Driver current limit = 1 A
%
% COMMENT THIS LINE:
%
%       Motor rated-current limit = 4.8 A
%
% -------------------------------------------------------------------------

case2.maximumCurrent = 1.0;     % DRIVER LIMIT - COMMENT FOR 4.8 A


if ~isfield(case2,'maximumCurrent')

    case2.maximumCurrent = ...
        motor.ratedCurrent;

end


if abs(case2.maximumCurrent - 1.0) < 1e-9

    case2.currentLimitSource = ...
        'Driver limit';

elseif abs( ...
        case2.maximumCurrent - ...
        motor.ratedCurrent ...
        ) < 1e-9

    case2.currentLimitSource = ...
        'Motor rated current';

else

    case2.currentLimitSource = ...
        'Custom current limit';

end


%% ========================================================================
%  22. CASE 2 VOLTAGE SWEEP
%  ========================================================================

commandedVoltage2 = linspace( ...
    case2.initialVoltage, ...
    case2.finalVoltage, ...
    simulation.numberOfOperatingPoints ...
).';


loadTorque2 = ...
    case2.loadTorque * ...
    ones(size(commandedVoltage2));


%% ========================================================================
%  23. CASE 2 STEADY-STATE SOLUTION
%  ========================================================================

numberOfSamples2 = ...
    length(commandedVoltage2);


current2 = ...
    zeros(numberOfSamples2,1);


angularVelocity2 = ...
    zeros(numberOfSamples2,1);


effectiveVoltage2 = ...
    zeros(numberOfSamples2,1);


currentLimitActive2 = ...
    false(numberOfSamples2,1);


stalledState2 = ...
    false(numberOfSamples2,1);


for k = 1:numberOfSamples2

    [ ...
        current2(k), ...
        angularVelocity2(k), ...
        effectiveVoltage2(k), ...
        currentLimitActive2(k), ...
        stalledState2(k) ...
    ] = steadyStateOperatingPoint( ...
        commandedVoltage2(k), ...
        loadTorque2(k), ...
        motor, ...
        case2.minimumCurrent, ...
        case2.maximumCurrent ...
    );

end


%% ========================================================================
%  24. CASE 2 OUTPUT VARIABLES
%  ========================================================================

motorRPM2 = ...
    angularVelocity2 * ...
    60/(2*pi);


motorTorque2 = ...
    motor.Kt .* ...
    current2;


backEMF2 = ...
    motor.Ke .* ...
    angularVelocity2;


frictionTorque2 = ...
    motor.B .* ...
    angularVelocity2;


electricalPower2 = ...
    effectiveVoltage2 .* ...
    current2;


motorMechanicalPower2 = ...
    motorTorque2 .* ...
    angularVelocity2;


%% ========================================================================
%  25. CASE 2 RESULTS
%  ========================================================================

fprintf('\n============================================================\n');
fprintf('CASE 2 - VOLTAGE CHARACTERIZATION\n');
fprintf('ZERO LOAD - 6 V TO 24 V\n');
fprintf('============================================================\n');


fprintf( ...
    'Initial voltage:               %.2f V\n', ...
    case2.initialVoltage ...
);


fprintf( ...
    'Final voltage:                 %.2f V\n', ...
    case2.finalVoltage ...
);


fprintf( ...
    'Current limit:                 %.2f A\n', ...
    case2.maximumCurrent ...
);


fprintf( ...
    'Current limit source:          %s\n', ...
    case2.currentLimitSource ...
);


fprintf( ...
    'Speed at %.1f V:               %.2f RPM\n', ...
    case2.initialVoltage, ...
    motorRPM2(1) ...
);


fprintf( ...
    'Speed at %.1f V:               %.2f RPM\n', ...
    case2.finalVoltage, ...
    motorRPM2(end) ...
);


fprintf( ...
    'Current at %.1f V:             %.4f A\n', ...
    case2.initialVoltage, ...
    current2(1) ...
);


fprintf( ...
    'Current at %.1f V:             %.4f A\n', ...
    case2.finalVoltage, ...
    current2(end) ...
);


%% ========================================================================
%  26. CASE 2 PLOT DATA
%  ========================================================================

numberPlotPoints2 = min( ...
    simulation.maximumPlotPoints, ...
    length(commandedVoltage2) ...
);


plotIndex2 = ...
    unique( ...
        round( ...
            linspace( ...
                1, ...
                length(commandedVoltage2), ...
                numberPlotPoints2 ...
            ) ...
        ) ...
    );


%% ========================================================================
%  27. FIGURA 2 - VELOCIDAD DEL ROTOR VS VOLTAJE
%  ========================================================================

figure2 = figure( ...
    'Name', ...
    'CASO 2 - Voltaje vs velocidad del rotor', ...
    'NumberTitle','off', ...
    'Color','white', ...
    'Renderer','painters' ...
);


set( ...
    figure2, ...
    'Position', ...
    [120 100 1000 650] ...
);


ax21 = axes( ...
    'Parent', ...
    figure2 ...
);


plot( ...
    ax21, ...
    commandedVoltage2(plotIndex2), ...
    motorRPM2(plotIndex2), ...
    'LineWidth',1.8 ...
);


hold(ax21,'on');


yline( ...
    ax21, ...
    motor.ratedSpeedRPM, ...
    ':', ...
    sprintf( ...
        'Velocidad nominal: %.0f RPM', ...
        motor.ratedSpeedRPM ...
    ), ...
    'LineWidth',1.1 ...
);


hold(ax21,'off');


grid(ax21,'on');

box(ax21,'on');


xlabel( ...
    ax21, ...
    'Voltaje aplicado [V]' ...
);


ylabel( ...
    ax21, ...
    'Velocidad del rotor [RPM]' ...
);


title( ...
    ax21, ...
    sprintf( ...
        ['CASO 2 - Voltaje de 6 a 24 V - Sin Torque Aplicado, ' ...
         'Límite de Corriente = %.1f A'], ...
        case2.maximumCurrent ...
    ) ...
);


xlim( ...
    ax21, ...
    [ ...
        case2.initialVoltage ...
        case2.finalVoltage ...
    ] ...
);


set( ...
    ax21, ...
    'FontSize',11, ...
    'LineWidth',0.8, ...
    'Layer','top' ...
);


drawnow;


%% ========================================================================
%  28. RESULTS TABLES
%  ========================================================================

case1Results = table( ...
    loadTorque1, ...
    commandedVoltage1, ...
    effectiveVoltage1, ...
    current1, ...
    angularVelocity1, ...
    motorRPM1, ...
    backEMF1, ...
    motorTorque1, ...
    frictionTorque1, ...
    netTorque1, ...
    electricalPower1, ...
    motorMechanicalPower1, ...
    loadMechanicalPower1, ...
    efficiency1, ...
    currentLimitActive1, ...
    stalledState1, ...
    'VariableNames', { ...
        'LoadTorque_Nm', ...
        'CommandedVoltage_V', ...
        'EffectiveVoltage_V', ...
        'Current_A', ...
        'AngularVelocity_rad_s', ...
        'Speed_RPM', ...
        'BackEMF_V', ...
        'MotorTorque_Nm', ...
        'FrictionTorque_Nm', ...
        'NetTorque_Nm', ...
        'ElectricalPower_W', ...
        'MotorMechanicalPower_W', ...
        'LoadMechanicalPower_W', ...
        'SteadyStateEfficiency_percent', ...
        'CurrentLimitActive', ...
        'Stalled' ...
    } ...
);


case2Results = table( ...
    commandedVoltage2, ...
    effectiveVoltage2, ...
    current2, ...
    angularVelocity2, ...
    motorRPM2, ...
    backEMF2, ...
    motorTorque2, ...
    frictionTorque2, ...
    electricalPower2, ...
    motorMechanicalPower2, ...
    currentLimitActive2, ...
    stalledState2, ...
    'VariableNames', { ...
        'CommandedVoltage_V', ...
        'EffectiveVoltage_V', ...
        'Current_A', ...
        'AngularVelocity_rad_s', ...
        'Speed_RPM', ...
        'BackEMF_V', ...
        'MotorTorque_Nm', ...
        'FrictionTorque_Nm', ...
        'ElectricalPower_W', ...
        'MotorMechanicalPower_W', ...
        'CurrentLimitActive', ...
        'Stalled' ...
    } ...
);


%% ========================================================================
%  29. PARAMETER TABLE
%  ========================================================================

parameterName = { ...
    'Motor model'; ...
    'Nominal voltage'; ...
    'Rated speed'; ...
    'Rated torque'; ...
    'Rated current'; ...
    'Rated power'; ...
    'Peak torque'; ...
    'Peak current'; ...
    'Torque constant Kt'; ...
    'Back-EMF constant Ke'; ...
    'Resistance R'; ...
    'Inductance L'; ...
    'Motor rotor inertia'; ...
    'External load inertia'; ...
    'Total equivalent inertia'; ...
    'Viscous friction coefficient B'; ...
    'Number of steady-state points'; ...
    'Case 1 voltage'; ...
    'Case 1 initial load torque'; ...
    'Case 1 final load torque'; ...
    'Case 1 current limit'; ...
    'Case 1 current limit source'; ...
    'Case 2 initial voltage'; ...
    'Case 2 final voltage'; ...
    'Case 2 load torque'; ...
    'Case 2 current limit'; ...
    'Case 2 current limit source' ...
};


parameterValue = { ...
    motor.model; ...
    motor.nominalVoltage; ...
    motor.ratedSpeedRPM; ...
    motor.ratedTorque; ...
    motor.ratedCurrent; ...
    motor.ratedPower; ...
    motor.peakTorque; ...
    motor.peakCurrent; ...
    motor.Kt; ...
    motor.Ke; ...
    motor.R; ...
    motor.L; ...
    motor.Jmotor; ...
    motor.Jload; ...
    motor.J; ...
    motor.B; ...
    simulation.numberOfOperatingPoints; ...
    case1.voltage; ...
    case1.initialLoadTorque; ...
    case1.finalLoadTorque; ...
    case1.maximumCurrent; ...
    case1.currentLimitSource; ...
    case2.initialVoltage; ...
    case2.finalVoltage; ...
    case2.loadTorque; ...
    case2.maximumCurrent; ...
    case2.currentLimitSource ...
};


parameterUnit = { ...
    '-'; ...
    'V'; ...
    'RPM'; ...
    'N*m'; ...
    'A'; ...
    'W'; ...
    'N*m'; ...
    'A'; ...
    'N*m/A'; ...
    'V/(rad/s)'; ...
    'ohm'; ...
    'H'; ...
    'kg*m^2'; ...
    'kg*m^2'; ...
    'kg*m^2'; ...
    'N*m*s/rad'; ...
    '-'; ...
    'V'; ...
    'N*m'; ...
    'N*m'; ...
    'A'; ...
    '-'; ...
    'V'; ...
    'V'; ...
    'N*m'; ...
    'A'; ...
    '-' ...
};


parameterTable = table( ...
    parameterName, ...
    parameterValue, ...
    parameterUnit, ...
    'VariableNames', { ...
        'Parameter', ...
        'Value', ...
        'Unit' ...
    } ...
);


%% ========================================================================
%  30. SAVE ONLY THE TWO FIGURES
%  ========================================================================

exportgraphics( ...
    figure1, ...
    output.figure1File, ...
    'Resolution', ...
    output.figureResolution ...
);


exportgraphics( ...
    figure2, ...
    output.figure2File, ...
    'Resolution', ...
    output.figureResolution ...
);


%% ========================================================================
%  31. SAVE RESULTS TO EXCEL
%  ========================================================================

if isfile(output.excelFile)

    delete(output.excelFile);

end


writetable( ...
    parameterTable, ...
    output.excelFile, ...
    'Sheet', ...
    'Motor_Parameters' ...
);


writetable( ...
    case1Results, ...
    output.excelFile, ...
    'Sheet', ...
    'Case_1_Load_Torque' ...
);


writetable( ...
    case2Results, ...
    output.excelFile, ...
    'Sheet', ...
    'Case_2_Voltage' ...
);


%% ========================================================================
%  32. FINAL INFORMATION
%  ========================================================================

fprintf('\n============================================================\n');
fprintf('FILES SAVED SUCCESSFULLY\n');
fprintf('============================================================\n');


fprintf( ...
    'Figure 1: %s\n', ...
    output.figure1File ...
);


fprintf( ...
    'Figure 2: %s\n', ...
    output.figure2File ...
);


fprintf( ...
    'Excel:    %s\n', ...
    output.excelFile ...
);


fprintf('\n============================================================\n');
fprintf('CURRENT LIMIT SELECTION\n');
fprintf('============================================================\n');


fprintf( ...
    'CASE 1 current limit: %.2f A - %s\n', ...
    case1.maximumCurrent, ...
    case1.currentLimitSource ...
);


fprintf( ...
    'CASE 2 current limit: %.2f A - %s\n', ...
    case2.maximumCurrent, ...
    case2.currentLimitSource ...
);


fprintf('\nActive line     = 1 A driver limit\n');
fprintf('Commented line  = 4.8 A motor rated-current limit\n');


fprintf( ...
    '\nCASE 1 maximum electromagnetic torque: %.4f N*m\n', ...
    motor.Kt * ...
    case1.maximumCurrent ...
);


%% ========================================================================
%  LOCAL FUNCTION
%
%  STEADY-STATE OPERATING POINT
%
%  The steady-state equations are:
%
%       0 = V - R*i - Ke*omega
%
%       0 = Kt*i - B*omega - Tload
%
%
%  NORMAL REGION:
%
%       Voltage = commanded voltage
%
%
%  CURRENT-LIMITED REGION:
%
%       i = Imax
%
%
%  STALL:
%
%       omega = 0
%
% ========================================================================

function [ ...
    current, ...
    angularVelocity, ...
    effectiveVoltage, ...
    currentLimitActive, ...
    stalled ...
    ] = steadyStateOperatingPoint( ...
        commandedVoltage, ...
        loadTorque, ...
        motor, ...
        minimumCurrent, ...
        maximumCurrent ...
    )


    tolerance = 1e-10;


    %% Ensure nonnegative inputs

    commandedVoltage = ...
        max( ...
            commandedVoltage, ...
            0 ...
        );


    loadTorque = ...
        max( ...
            loadTorque, ...
            0 ...
        );


    %% ====================================================================
    %  UNCONSTRAINED STEADY-STATE SOLUTION
    %
    %       V = R*i + Ke*omega
    %
    %       Kt*i = B*omega + Tload
    %
    %
    %  Eliminating current:
    %
    %                   V - R*Tload/Kt
    %       omega = -------------------------
    %                  Ke + R*B/Kt
    %
    % =====================================================================

    denominator = ...
        motor.Ke + ...
        motor.R * ...
        motor.B / ...
        motor.Kt;


    unconstrainedAngularVelocity = ...
        ( ...
            commandedVoltage - ...
            motor.R * ...
            loadTorque / ...
            motor.Kt ...
        ) / ...
        denominator;


    %% Calculate required current

    if unconstrainedAngularVelocity > 0

        unconstrainedCurrent = ...
            ( ...
                loadTorque + ...
                motor.B * ...
                unconstrainedAngularVelocity ...
            ) / ...
            motor.Kt;

    else

        % At stall:
        %
        %       omega = 0
        %
        % therefore:
        %
        %       i = V/R

        unconstrainedCurrent = ...
            commandedVoltage / ...
            motor.R;

    end


    %% ====================================================================
    %  NORMAL VOLTAGE-LIMITED OPERATING REGION
    % =====================================================================

    if ...
        unconstrainedAngularVelocity > 0 ...
        && ...
        unconstrainedCurrent <= ...
        maximumCurrent + tolerance


        angularVelocity = ...
            unconstrainedAngularVelocity;


        current = ...
            min( ...
                max( ...
                    unconstrainedCurrent, ...
                    minimumCurrent ...
                ), ...
                maximumCurrent ...
            );


        effectiveVoltage = ...
            commandedVoltage;


        currentLimitActive = ...
            false;


        stalled = ...
            false;


        return;

    end


    %% ====================================================================
    %  CURRENT-LIMITED OPERATING REGION
    %
    %       i = Imax
    %
    %
    %  Mechanical steady-state equation:
    %
    %       Kt*Imax = B*omega + Tload
    %
    %
    %  Therefore:
    %
    %                  Kt*Imax - Tload
    %       omega = --------------------------
    %                          B
    %
    % =====================================================================

    if unconstrainedCurrent > maximumCurrent

        current = ...
            maximumCurrent;


        currentLimitedAngularVelocity = ...
            ( ...
                motor.Kt * ...
                current - ...
                loadTorque ...
            ) / ...
            motor.B;


        if currentLimitedAngularVelocity > 0

            requiredVoltage = ...
                motor.R * ...
                current + ...
                motor.Ke * ...
                currentLimitedAngularVelocity;


            if requiredVoltage <= ...
                    commandedVoltage + tolerance


                angularVelocity = ...
                    currentLimitedAngularVelocity;


                effectiveVoltage = ...
                    max( ...
                        requiredVoltage, ...
                        0 ...
                    );


                currentLimitActive = ...
                    true;


                stalled = ...
                    false;


                return;

            end

        end

    end


    %% ====================================================================
    %  STALL CONDITION
%  ========================================================================

    angularVelocity = 0;


    current = ...
        commandedVoltage / ...
        motor.R;


    current = ...
        min( ...
            max( ...
                current, ...
                minimumCurrent ...
            ), ...
            maximumCurrent ...
        );


    effectiveVoltage = ...
        motor.R * ...
        current;


    currentLimitActive = ...
        current >= ...
        maximumCurrent - tolerance ...
        && ...
        commandedVoltage > ...
        effectiveVoltage + tolerance;


    stalled = true;

end